### PR TITLE
Fix remote outgoing window handling

### LINKED ISSUE #15: Implementation issues?
Hello, 

while experimenting with this library I noticed the following two points and would like to ask if I missed something or if this is an issue with the implementation: 

- remote-outgoing-window update condition 
- protocol might stop

**remote-outgoing-window update condition** 
According to the spec (http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-session-flow-control) the `remote-outgoing-window` should be update only if: 
-  a transfer frame is received 
- or a flow frame is received

Is there any reason why the `remote-outgoing-window` gets assigned to the incoming window of the session for example like  here: 
https://github.com/Azure/go-amqp/blob/6a20a079aa598260ec97857517635d5b02a20b6a/client.go#L717

**protocol might stop**

Assumption: 
- server `outgoing-window`: 100
- server  `incoming-window`: 100
- client `outgoing-window`: 1000
- client  `incoming-window`: 1000
- server sends one flow frame right before sending the transfer frames

Am I right with the assumption that the client will never reach this code 
https://github.com/Azure/go-amqp/blob/6a20a079aa598260ec97857517635d5b02a20b6a/client.go#L706-L708
because the `remote-outgoing-window` is updated here (like in the protocol spec defined): 
https://github.com/Azure/go-amqp/blob/6a20a079aa598260ec97857517635d5b02a20b6a/client.go#L632

Thank you in advance for your help in exploring this lib.

### PR DESCRIPTION
**Pull request by serbrech**
At moderate concurrency, we could eat up the session window which was defaulted to a low value (100)
This caused a nasty bug to manifest. the window values are stored as uint.
it is decremented at each transfer. in some cases the uint would loop to intMax.
Once the window would have such a high value, the client stops sending Flow frames, because it thinks its window is huge.
eventually, no messages would get sent, because the remote peer and the local peer are out of sync, and no flow is sent across to reconciliate their state.

This PR fixes the window decrement by stopping it at 0 to prevent looping to int max.

- removes 2 places in the code where go-amqp was pre-emptively setting the outgoing window, probably as a workaround to the uint looping to max int. it now relies on the protocol, only ever updating the remote outgoing window based on communication from the remote peer, as per the protocol.
- sets the DefaultWindow to 1000, as a more sensible value (ServiceBus endpoints advertise a window of 5000)

fixes #15

### CODE REVIEW

File: session.go [hunk 1]
```diff
@@ -156,6 +156,10 @@ func (s *Session) mux(remoteBegin *performBegin) {
 		txTransfer := s.txTransfer
 		// disable txTransfer if flow control windows have been exceeded
 		if remoteIncomingWindow == 0 || s.outgoingWindow == 0 {
+			debug(1, "TX(Session): Disabling txTransfer - window exceeded. remoteIncomingWindow:",
```
Comment (serbrech) [inline session.go:159]: was suspecting this to occur and added a debut trace, I think it's a wise one to keep anyway :)

File: session.go [hunk 2]
```diff
@@ -291,6 +295,7 @@ func (s *Session) mux(remoteBegin *performBegin) {
 				// initial-outgoing-id(endpoint) + incoming-window(flow) - next-outgoing-id(endpoint)"
 				remoteIncomingWindow = body.IncomingWindow - nextOutgoingID
 				remoteIncomingWindow += *body.NextIncomingID
+				debug(3, "RX(Session) Flow - remoteOutgoingWindow: %d remoteIncomingWindow: %d nextOutgoingID: %d", remoteOutgoingWindow, remoteIncomingWindow, nextOutgoingID)
```
Comment (serbrech) [inline session.go:298]: added more debug info to understand the state of the flow

File: session.go [hunk 3]
```diff
@@ -338,7 +343,10 @@ func (s *Session) mux(remoteBegin *performBegin) {
 				// as decrementing the remote-outgoing-window, and MAY
 				// (depending on policy) decrement its incoming-window."
 				nextIncomingID++
-				remoteOutgoingWindow--
+				// don't loop to intmax
+				if remoteOutgoingWindow > 0 {
+					remoteOutgoingWindow--
```
Comment (serbrech) [inline session.go:348]: protect outgoing window to loop to max int. ouch..

File: session.go [hunk 4]
```diff
@@ -351,10 +359,11 @@ func (s *Session) mux(remoteBegin *performBegin) {
 
 				// if this message is received unsettled and link rcv-settle-mode == second, add to handlesByRemoteDeliveryID
 				if !body.Settled && body.DeliveryID != nil && link.receiverSettleMode != nil && *link.receiverSettleMode == ModeSecond {
-					debug(1, "TX: adding handle to handlesByRemoteDeliveryID. linkCredit: %d", link.linkCredit)
+					debug(1, "TX(Session): adding handle to handlesByRemoteDeliveryID. linkCredit: %d", link.linkCredit)
 					handlesByRemoteDeliveryID[*body.DeliveryID] = body.Handle
 				}
 
+				debug(3, "TX(Session) Flow? remoteOutgoingWindow(%d) < s.incomingWindow(%d)/2\n", remoteOutgoingWindow, s.incomingWindow)
```
Comment (serbrech) [inline session.go:366]: log the decision to send a Flow frame.
this is where the remoteOutgoingWindow showed to be max int.
it then never reaches incomingWindow/2, and we stop sending flow frames, which stops the protocol in some cases

File: session.go [hunk 5]
```diff
@@ -422,7 +430,10 @@ func (s *Session) mux(remoteBegin *performBegin) {
 			// its next-outgoing-id, decrement its remote-incoming-window,
 			// and MAY (depending on policy) decrement its outgoing-window."
 			nextOutgoingID++
-			remoteIncomingWindow--
+			// don't decrement if we're at 0 or we could loop to int max
+			if remoteIncomingWindow != 0 {
```
Comment (serbrech) [inline session.go:434]: same protection on incoming window, although I did not see it happening.

File: session.go [hunk 6]
```diff
@@ -434,7 +445,6 @@ func (s *Session) mux(remoteBegin *performBegin) {
 				fr.OutgoingWindow = s.outgoingWindow
 				debug(1, "TX(Session) - tx: %s", fr)
 				s.txFrame(fr, nil)
-				remoteOutgoingWindow = s.incomingWindow
```
Comment (serbrech) [inline session.go:437]: as noted in #15 this was not as per protocol. the remoteOutgoingWindow is supposed to reflect the remote peer state. we cannot just updated it to incomingWindow.
the remotePeer lets us know where it's at in flow frames, and that's the only place we should update it.

File: session.go [hunk 7]
```diff
@@ -366,7 +375,6 @@ func (s *Session) mux(remoteBegin *performBegin) {
 					}
 					debug(1, "TX(Session): %s", flow)
 					s.txFrame(flow, nil)
-					remoteOutgoingWindow = s.incomingWindow
```
Comment (serbrech) [inline session.go:369]: same. we should not update the remoteOutgoingWindow ourselves. trust the protocol :)

**Review by jhendrixMSFT — APPROVED** [review]

**Review by richardpark-msft — COMMENTED** [review]
I think we really need some test cases in here so I can visualize what the sequence of frames to responses is.

**Comment by richardpark-msft** [comment]
> I think we really need some test cases in here so I can visualize what the sequence of frames to responses is.

After talking about this more I think (what we can reasonably do) is to have the debug() trail of logs for the failure and then we can figure out how to create a testable case afterwards. 

Approving.

**Comment by serbrech** [comment]
here are trace sample of this happening : 

```
12:46:13.796645 RX: add 165 to inflight
12:46:13.796773 TX: Disposition{Role: Receiver, First: 165, Last: <nil>, Settled: false, State: Accepted, Batchable: false}
12:46:13.797905 RX(Session): Transfer{Handle: 0, DeliveryID: 166, DeliveryTag: "\xc9`\x8c*\x18\a\xa9G\x97\xb2\xae\xd7\x15K\xf3\xe4", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209}
12:46:13.797976 RX(Session) Transfer{Handle: 0, DeliveryID: 166, DeliveryTag: "\xc9`\x8c*\x18\a\xa9G\x97\xb2\xae\xd7\x15K\xf3\xe4", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209} - remoteOutgoingWindow: 2 nextIncomingID: 168
12:46:13.798005 TX: adding handle to handlesByRemoteDeliveryID. linkCredit: 334
12:46:13.798079 RX: Transfer{Handle: 0, DeliveryID: 166, DeliveryTag: "\xc9`\x8c*\x18\a\xa9G\x97\xb2\xae\xd7\x15K\xf3\xe4", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209}
12:46:13.798214 deliveryID 166 before push to receiver - deliveryCount : 166 - linkCredit: 334, len(messages): 0, len(inflight): 3
12:46:13.798252 deliveryID 166 after push to receiver - deliveryCount : 166 - linkCredit: 334, len(messages): 0, len(inflight): 3
12:46:13.798272 Receive() blocking 166
12:46:13.798288 deliveryID 0 before exit - deliveryCount : 167 - linkCredit: 333, len(messages): 0
12:46:13.798371 RX: add 166 to inflight
12:46:13.798449 TX: Disposition{Role: Receiver, First: 166, Last: <nil>, Settled: false, State: Accepted, Batchable: false}
12:46:13.890780 RX(Session): Transfer{Handle: 0, DeliveryID: 167, DeliveryTag: "\xc8\xc62\xdf:G\xf7F\x85\xf1\xdcu\x9e\xfc\x9b\xeb", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209}
12:46:13.890904 RX(Session) Transfer{Handle: 0, DeliveryID: 167, DeliveryTag: "\xc8\xc62\xdf:G\xf7F\x85\xf1\xdcu\x9e\xfc\x9b\xeb", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209} - remoteOutgoingWindow: 1 nextIncomingID: 169
12:46:13.890966 TX: adding handle to handlesByRemoteDeliveryID. linkCredit: 333
12:46:13.891073 TX(Session): Flow{NextIncomingID: 169, IncomingWindow: 5, NextOutgoingID: 0, OutgoingWindow: 5, Handle: <nil>, DeliveryCount: <nil>, LinkCredit: <nil>, Available: <nil>, Drain: false, Echo: false, Properties: map[]}
12:46:13.891097 RX: Transfer{Handle: 0, DeliveryID: 167, DeliveryTag: "\xc8\xc62\xdf:G\xf7F\x85\xf1\xdcu\x9e\xfc\x9b\xeb", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209}
12:46:13.891124 (BAD) - TX(Session): updating remoteOutgoingWindow 5
12:46:13.891299 deliveryID 167 before push to receiver - deliveryCount : 167 - linkCredit: 333, len(messages): 0, len(inflight): 4
12:46:13.891369 deliveryID 167 after push to receiver - deliveryCount : 167 - linkCredit: 333, len(messages): 0, len(inflight): 4
12:46:13.891401 Receive() blocking 167
12:46:13.891405 deliveryID 0 before exit - deliveryCount : 168 - linkCredit: 332, len(messages): 0
12:46:13.891531 RX: add 167 to inflight
12:46:13.891659 TX: Disposition{Role: Receiver, First: 167, Last: <nil>, Settled: false, State: Accepted, Batchable: false}
12:46:13.937728 RX(Session): Transfer{Handle: 0, DeliveryID: 168, DeliveryTag: "\xc8#\x84\xe9\x15P\xd1@\xa5\xc4N\xfd\x06\xab}\x1b", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209}
12:46:13.937814 RX(Session) Transfer{Handle: 0, DeliveryID: 168, DeliveryTag: "\xc8#\x84\xe9\x15P\xd1@\xa5\xc4N\xfd\x06\xab}\x1b", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209} - remoteOutgoingWindow: 4 nextIncomingID: 170
12:46:13.937848 TX: adding handle to handlesByRemoteDeliveryID. linkCredit: 332
12:46:13.937898 RX(Session): Disposition{Role: Sender, First: 163, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:13.937954 RX: Transfer{Handle: 0, DeliveryID: 168, DeliveryTag: "\xc8#\x84\xe9\x15P\xd1@\xa5\xc4N\xfd\x06\xab}\x1b", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: true, Payload [size]: 10209}
12:46:13.938107 deliveryID 168 before push to receiver - deliveryCount : 168 - linkCredit: 332, len(messages): 0, len(inflight): 5
12:46:13.938142 deliveryID 168 after push to receiver - deliveryCount : 168 - linkCredit: 332, len(messages): 0, len(inflight): 5
12:46:13.938159 deliveryID 0 before exit - deliveryCount : 169 - linkCredit: 331, len(messages): 0
12:46:13.938178 Receive() blocking 168
12:46:13.938194 RX: Disposition{Role: Sender, First: 163, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:13.938267 RX: add 168 to inflight
12:46:13.938284 Receive() deleted unsettled 163
12:46:13.938333 TX: Disposition{Role: Receiver, First: 168, Last: <nil>, Settled: false, State: Accepted, Batchable: false}
12:46:14.002779 RX(Session): Disposition{Role: Sender, First: 164, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.002855 RX: Disposition{Role: Sender, First: 164, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.002969 Receive() deleted unsettled 164
12:46:14.133748 RX(Session): Disposition{Role: Sender, First: 165, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.133870 RX(Session): Disposition{Role: Sender, First: 166, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.133989 RX: Disposition{Role: Sender, First: 165, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.134089 RX: Disposition{Role: Sender, First: 166, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.134137 Receive() deleted unsettled 165
12:46:14.134204 Receive() deleted unsettled 166
12:46:14.134212 RX(Session): Disposition{Role: Sender, First: 167, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.134392 RX: Disposition{Role: Sender, First: 167, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.134526 Receive() deleted unsettled 167
12:46:14.179417 RX(Session): Disposition{Role: Sender, First: 168, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.179578 RX: Disposition{Role: Sender, First: 168, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
12:46:14.179785 Receive() deleted unsettled 168
12:48:48.288255 RX(Session): Flow{NextIncomingID: 169, IncomingWindow: 5000, NextOutgoingID: 1, OutgoingWindow: 100, Handle: <nil>, DeliveryCount: <nil>, LinkCredit: <nil>, Available: <nil>, Drain: false, Echo: true, Properties: map[]}
12:48:48.288350 TX(Session): Flow{NextIncomingID: 169, IncomingWindow: 5000, NextOutgoingID: 1, OutgoingWindow: 100, Handle: <nil>, DeliveryCount: <nil>, LinkCredit: <nil>, Available: <nil>, Drain: false, Echo: true, Properties: map[]}
12:48:48.288377 (GOOD) - RX(Session) Flow - Updating remoteOutgoingWindow 100 -> 100
12:48:48.288434 RX(Session) Flow - remoteOutgoingWindow: 100 remoteIncomingWindow: 5000 nextOutgoingID: 169
12:48:48.288499 TX: Flow{NextIncomingID: 1, IncomingWindow: 100, NextOutgoingID: 169, OutgoingWindow: 100, Handle: <nil>, DeliveryCount: <nil>, LinkCredit: <nil>, Available: <nil>, Drain: false, Echo: false, Properties: map[]}


.... the entire protocol is blocked no more flows happening.
```

**Comment by myusuf3** [comment]
Can this be attributed fix for  https://github.com/Azure/go-amqp/issues/25 I would to see if this fixed the scenario I described here.

**Comment by jhendrixMSFT** [comment]
@myusuf3 based on the description in #25 it seems likely.  Can you try it?

**Comment by ogero** [comment]
> @myusuf3 based on the description in #25 it seems likely. Can you try it?

Sorry, I missed your comment here before tagging you at https://github.com/Azure/go-amqp/issues/25#issuecomment-922060390.  
I can confirm [v0.13.13](https://github.com/Azure/go-amqp/releases/tag/v0.13.13) fixes #25 
Thanks for the patch!

**Comment by jhendrixMSFT** [comment]
Thanks for confirming, will close.
