### PR TITLE
fix reading application properties with ULong type

### LINKED ISSUE #119: Cannot decode a valid AMQP message
Hello and thank you for this great library!
I'm using a Java library to publish a message to ActiveMQ via AMQP 1.0: Swift MQ.

I cannot decode the following message, it seems that the ApplicationProperties are decoded wrongly ( it is not read as a composite type ).

```
\x00\x80\x00\x00\x00\x00\x00\x00\x00p\xc0\x07\x05AP\x04@BC\x00\x80\x00\x00\x00\x00\x00\x00\x00s\xc0*\x03\xa1\x187735812932138480283/1/12@\xa1\x0cActiveMQ.DLQ\x00\x80\x00\x00\x00\x00\x00\x00\x00t\xc1H\x08\xa1\x06prop01\xa1\x06val001\xa1\x07prop002\xa1\x02v2\xa1\rprop000000003\x81\x00\x00\x00\x00\x00\x01\x86\xa0\xa1\x05prop4\xa1\tval000004\x00\x80\x00\x00\x00\x00\x00\x00\x00w\xa1\x99{"id":"000000000","prop4":"val000004","prop002Code":"v2","___prop000000003":10.0,"_______prop000000003":"10.0","prop0005":100,"_________prop01":"val001"}
```

Or, in an int representation:

```
0, 128, 0, 0, 0, 0, 0, 0, 0, 112, 192, 7, 5, 65, 80, 4, 64, 66, 67, 0, 128, 0, 0, 0, 0, 0, 0, 0, 115, 192, 42, 3, 161, 24, 55, 55, 51, 53, 56, 49, 50, 57, 51, 50, 49, 51, 56, 52, 56, 48, 50, 56, 51, 47, 49, 47, 49, 50, 64, 161, 12, 65, 99, 116, 105, 118, 101, 77, 81, 46, 68, 76, 81, 0, 128, 0, 0, 0, 0, 0, 0, 0, 116, 193, 72, 8, 161, 6, 112, 114, 111, 112, 48, 49, 161, 6, 118, 97, 108, 48, 48, 49, 161, 7, 112, 114, 111, 112, 48, 48, 50, 161, 2, 118, 50, 161, 13, 112, 114, 111, 112, 48, 48, 48, 48, 48, 48, 48, 48, 51, 129, 0, 0, 0, 0, 0, 1, 134, 160, 161, 5, 112, 114, 111, 112, 52, 161, 9, 118, 97, 108, 48, 48, 48, 48, 48, 52, 0, 128, 0, 0, 0, 0, 0, 0, 0, 119, 161, 153, 123, 34, 105, 100, 34, 58, 34, 48, 48, 48, 48, 48, 48, 48, 48, 48, 34, 44, 34, 112, 114, 111, 112, 52, 34, 58, 34, 118, 97, 108, 48, 48, 48, 48, 48, 52, 34, 44, 34, 112, 114, 111, 112, 48, 48, 50, 67, 111, 100, 101, 34, 58, 34, 118, 50, 34, 44, 34, 95, 95, 95, 112, 114, 111, 112, 48, 48, 48, 48, 48, 48, 48, 48, 51, 34, 58, 49, 48, 46, 48, 44, 34, 95, 95, 95, 95, 95, 95, 95, 112, 114, 111, 112, 48, 48, 48, 48, 48, 48, 48, 48, 51, 34, 58, 34, 49, 48, 46, 48, 34, 44, 34, 112, 114, 111, 112, 48, 48, 48, 53, 34, 58, 49, 48, 48, 44, 34, 95, 95, 95, 95, 95, 95, 95, 95, 95, 112, 114, 111, 112, 48, 49, 34, 58, 34, 118, 97, 108, 48, 48, 49, 34, 125
```

I'm looking forward to being able to share messages across the 2 platforms!
Thank you for your help and precious time.

EDIT:
ActiveMQ shows the message application properties correctly, hence the AMQP message shall be a valid one, at least up to the Application properties that fail to decode with go-amqp.

### PR DESCRIPTION
**Pull request by tux-mind**
fixes #119

It seems that there is a bug when decoding maps with the type encoded as ULong instead of SmallULong.
I added a test to reproduce the issue and a fix in the affected code.

I didn't have a 0 length map to test it with, so I'm not sure about the returned size for the `TypeCodeUlong0` type, please check.
Thank you again for this library!

### CODE REVIEW

File: internal/encoding/types.go [hunk 1]
```diff
@@ -410,38 +410,38 @@ func (f *Filter) Unmarshal(r *buffer.Buffer) error {
...
 	if buf[0] != 0 {
-		return 0, fmt.Errorf("invalid composite header %02x", buf[0])
+		return 0, 0, fmt.Errorf("invalid composite header %02x", buf[0])
 	}
 
 	// copied from readUlong to avoid allocations
 	t := AMQPType(buf[1])
 	if t == TypeCodeUlong0 {
-		return 0, nil
+		return 0, 2, nil
```
Comment (tux-mind) [inline internal/encoding/types.go:425]: This might be wrong, the old behaviour was to skip 3 bytes, but the header is 2 bytes long as far as I can tell.
I might be wrong though.

Comment (jhendrixMSFT) [reply internal/encoding/types.go:425]: The three bytes would be correct for the case where the encoded length of the message type is a `smallulong`.
```
00 - composite type prefix
83 - smallulong
xx - smallulong value
```

http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-types-v1.0-os.html#type-ulong

From your repro, application properties is encoded as an 8-byte ulong (`0, 128, 0, 0, 0, 0, 0, 0, 0, 116`).

It appears that Azure service bus encodes application properties size as a smallulong.  I don't see anything in the AMQP 1.0 spec that restricts the size to a smallulong so this should be fine.

**Review by jhendrixMSFT — APPROVED** [review]

File: internal/encoding/types.go (hunk 1 above)
Comment (jhendrixMSFT) [reply internal/encoding/types.go:425]: When unmarshalling a Message, ulong0 isn't valid as a type in that context, so even if the size is wrong here it won't matter.
